{% set name = "chemlite" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8584261048df41a101587773e7145d7adf8ba15600287a9506e2d975ab908571

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - brs_utils

test:
  source_files:
    - tests
  imports:
    - chemlite
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/chemlite
  summary: Basic representation of compounds, reactions, pathways
  license: MIT
  license_file: LICENSE
  doc_url: https://brsynth.github.io/chemlite
  dev_url: https://github.com/brsynth/chemlite

extra:
  recipe-maintainers:
    - breakthewall
